repository:
  reponame: https://raw.githubusercontent.com/aMMokschaf/yamls/main/
  user:
    username: marcel.singer@hs-bochum.de
    accessToken: '{"access_token":"00132854b356fc04cd72baca27084cbc350d048f","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}'
bot:
  port: 4567
