user:
  username: KubeLinterBot #nötig?
  accessToken: '{"access_token":"ca4e2cedec5e6757c0268fa82872cdc7b14f322a","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}'
bot:
  port: 4567
repositories:
- name: yamls
  owner: aMMokschaf
  webhook:
    secret: testsecret
    events: []
    address: ""
